# -*- coding: utf-8 -*-
"""Programming_Assingment2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x970ujvD3YthnAM54doEOeRAleKjWUsk

**1. Write a Python program to convert kilometers to miles?**
"""

kilometers = float(input("Enter the measure in Kilometers you want to covert in miles: "))

result = kilometers * 0.6214

rounded_result = round(result, 2)

print(f"The result in miles is: {rounded_result} miles")

"""**2. Write a Python program to convert Celsius to Fahrenheit?**"""

temperature_input = float(input("Enter the temperature in degree celsius: "))

temperature_in_degrees_Fahrenheit = (temperature_input * 9/5) + 32

print(f"The temperature in degrees fahrenheit is: {temperature_in_degrees_Fahrenheit}")

"""**3. Write a Python program to display calendar?**"""

import calendar

year = int(input("Enter the year: "))
month = int(input("Enter the month: "))

print(calendar.month(year, month))

"""**4. Write a Python program to solve quadratic equation?**"""

import cmath

a = int(input("Enter the value of a: "))
b = int(input("Enter the value of b: "))
c = int(input("Enter the value of c: "))

d = (b**2) - 4*a*c

sol_1 = (-b - cmath.sqrt(d) / (2 * a))
sol_2 = (-b + cmath.sqrt(d) / (2 * a))

print("The roots of the equation ax^2+bx+c are: ")
print(sol_1)
print(sol_2)

"""**5. Write a Python program to swap two variables without temp variable?**"""

num_1 = int(input("Enter the value of num_1: "))
num_2 = int(input("Enter the value of num_2: "))

print("Before swapping")
print(f"Value of num_1: {num_1}", f" num_2: {num_2}")

num_1, num_2 = num_2, num_1

print("After swapping")
print(f"Value of num_1: {num_1}", f"num_2: {num_2}")